services:
  db:
    image: mysql:8.0
    container_name: chamados_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root  # Senha do root
      MYSQL_DATABASE: chamados
      MYSQL_USER: usuario
      MYSQL_PASSWORD: senha
    ports:
      - "3306:3306"
    volumes:
      - ./chamados.sql:/docker-entrypoint-initdb.d/chamados.sql
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
